- name: Dependencies fix for Jessie (get)
  get_url: url=http://repo.asis.io/jessie-updates/pool/main/libt/libtest-cgi-multipart-perl/libtest-cgi-multipart-perl_0.0.3-1_all.deb
           dest=/tmp/libtest-cgi-multipart-perl_0.0.3-1_all.deb mode=0644
  when: ansible_distribution_release == 'jessie'

- name: Dependencies fix for Jessie (deps)
  apt:  pkg={{ item }} state=latest
  with_items:
    - libmime-tools-perl
    - libuniversal-require-perl
    - libreadonly-perl
    - libparams-validate-perl

- name: Dependencies fix for Jessie (install)
  shell: dpkg -i /tmp/libtest-cgi-multipart-perl_0.0.3-1_all.deb
  when: ansible_distribution_release == 'jessie'

- name: Install Koha
  apt: pkg=koha-common state=latest force=yes

- name: Use our koha-sites.conf file
  template: src=koha-sites.conf.j2 dest=/etc/koha/koha-sites.conf mode=0644 owner=root

- name: Check for instance existence # we want the provisioning to be idempotent if already ran
  command: koha-list | grep {{ koha_instance_name }}
  register: result
  ignore_errors: True

- name: Create Koha instance
  shell:  koha-create --create-db {{ koha_instance_name }}
  when: result.stdout == ""
  notify: restart apache
